#
# GitHub Actions workflow.
#
# Perfoms the following actions on a pull request:
# * Lint the code
# * Run the tests
# * Confirm the build runs
#

name: PR Checks (ApiLayer)

on:
    pull_request:
        branches: [ main ]
        path: apps/apilayer/**

jobs:
    pr_checks:
        name: PR Checks (ApiLayer)
        runs-on: ubuntu-latest
        steps:
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 19

            - name: Checkout
              uses: actions/checkout@v2

            - name: Choose correct package
              run: cd apps/apilayer/ && npm run

            - name: Lint
              run:  npm run-script lint

            - name: Test
              run: npm run-script test

            - name: Build
              run: npm run-script build