#
# GitHub Actions workflow.
#
# Perfoms the following actions on a pull request:
# * Lint the code
# * Run the tests
# * Confirm the build runs
#

name: PR Checks (ApiLayer)

on:
    pull_request:
        branches: [ main ]
        path: apps/apilayer/**

jobs:
    pr_checks:
        name: PR Checks (ApiLayer)
        runs-on: ubuntu-latest
        steps:
            -   name: Install Node.js
                uses: actions/setup-node@v3
                with:
                    node-version: 19

            - name: Checkout
              uses: actions/checkout@v2

            - name: FontAwesome Auth
              run: echo @fortawesome:registry=https://npm.fontawesome.com/ //npm.fontawesome.com/:_authToken=${{ secrets.FONTAWESOME_AUTH_TOKEN }} > .npmrc

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                    version: 8
                    run_install: true

            - name: Choose correct package
              run: cd apps/apilayer/

            - name: Lint
              run:  pnpm run lint

            - name: Test
              run: pnpm run test

            - name: Build
              run: pnpm run build