name: ApiLayer

on:
    push:
        branches: [ main ]
        paths:
            - 'apps/apilayer/**'
jobs:
    release:
        steps:
            uses: apps/apilayer/.github/workflows/release.yml@main