#
# GitHub Actions workflow.
#
# Releases the package to npm when a push into main is detected.
# * Bump version number
# * Release to NPM
#

name: 'Release Package: ApiLayer'

on:
    push:
        branches: [ main ]
        path: 'apps/apilayer/**'

jobs:
    release:
        name: 'Release ApiLayer'
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            -   name: 'Install Node.js'
                uses: actions/setup-node@v3
                with:
                    node-version: 19

            -   name: 'Checkout'
                uses: actions/checkout@v2
                with:
                    token: ${{ secrets.GH_CI_CD_RELEASE }}

            -   name: 'FontAwesome Auth'
                run: echo -e "@fortawesome:registry=https://npm.fontawesome.com/\n//npm.fontawesome.com/:_authToken=${{ secrets.FONTAWESOME_AUTH_TOKEN }}" > .npmrc

            -   name: 'Install pnpm'
                uses: pnpm/action-setup@v2
                with:
                    version: 8
                    run_install: false

            -   name: 'Install dependencies'
                run: pnpm i --shamefully-hoist

            -   name: 'Read package.json'
                id: info
                uses: jaywcjlove/github-action-package@main

            -   name: 'Version Bump'
                uses: phips28/gh-action-bump-version@master
                env:
                    GITHUB_TOKEN: ${{ secrets.GH_CI_CD_RELEASE }}
                    PACKAGEJSON_DIR: apps/apilayer
                with:
                    major-wording: 'JLMAJOR'
                    minor-wording: 'feature,feat'
                    patch-wording: 'patch,fixes,misc,docs,refactor'    # Providing patch-wording will override commits
                    commit-message: 'Release ApiLayer: bumps ${{ steps.info.outputs.name }} version to {{version}} ::rocket::'

            -   name: 'Authenticate with NPM'
                run: echo -e "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

            -   name: 'Publishing package'
                run: cd apps/apilayer/ && pnpm publish --access public