#
# GitHub Actions workflow.
#
# Perfoms the following actions on a pull request:
# * Lint the code
# * Run the tests
# * Confirm the build runs
#

name: PR Checks (ApiLayer)

on:
    pull_request:
        branches: [ main ]
        path: apps/apilayer/**

jobs:
    pr_checks:
        name: PR Checks (ApiLayer)
        runs-on: ubuntu-latest
        steps:
            -   name: Install Node.js
                uses: actions/setup-node@v3
                with:
                    node-version: 19

            - name: Checkout
              uses: actions/checkout@v2

            - name: FontAwesome Auth
              run: echo -e "@fortawesome:registry=https://npm.fontawesome.com/\n//npm.fontawesome.com/:_authToken=${{ secrets.FONTAWESOME_AUTH_TOKEN }}" > .npmrc

            - name: Navigate to ApiLayer
              run: cd apps/apilayer/

            - name: Install dependencies
              run: npm ci

            - name: Lint
              run:  npm run lint

            - name: Test
              run: npm run test