name: ApiLayer

on:
    pull_request:
        branches: [ main ]
        paths:
            - 'apps/apilayer/**'
        jobs:
            pr_checks:
                steps:
                    name: PR Checks
                    uses: apps/apilayer/.github/workflows/pr.yml@main
    push:
        branches: [ main ]
        paths:
            - 'apps/apilayer/**'
        jobs:
            release:
                steps:
                    name: Release
                    uses: apps/apilayer/.github/workflows/release.yml@main