#
# GitHub Actions workflow.
#
# Releases the package to npm when a push into main is detected.
# * Perform the PR Checks
# * Bump version number
# * Release to NPM
#

name: Release (ApiLayer)

on:
    push:
        branches: [ main ]
        path: apps/apilayer/**

jobs:
    pr_checks:
        call-pr_checks:
            uses: ./pr.yml

    release:
        needs: [ pr_checks ]
        name: Release (ApiLayer)
        runs-on: ubuntu-latest
        steps:
            -   name: Install Node.js
                uses: actions/setup-node@v3
                with:
                    node-version: 19

            -   name: Install pnpm
                uses: pnpm/action-setup@v2
                with:
                    version: 7
                    run_install: false

            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Choose correct package
                run: cd apps/apilayer/

            -   name: Bumping version
                id: bumping-version
                uses: jpb06/bump-package@latest
                with:
                    major-keywords: VERSION_MAJOR
                    minor-keywords: feature,feat,minor
                    patch-keywords: fix,chore,bug,path,refactor,docs,test,misc
                    should-default-to-patch: true

            - name: Publishing package
              if: steps.bumping-version.outputs.bump-performed == 'true'
              run: pnpm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}