#
# GitHub Actions workflow.
#
# Releases the package to npm when a push into main is detected.
# * Bump version number
# * Release to NPM
#

env:
    PACKAGE: ApiLayer
    PATH: apps/apilayer

name: Release ($PACKAGE)

on:
    push:
        branches: [ main ]
        path: ${PATH}/**

jobs:
    release:
        name: Release $PACKAGE
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            -   name: 'Install Node.js ::coffee::'
                uses: actions/setup-node@v3
                with:
                    node-version: 19

            -   name: 'Checkout ::octocat::'
                uses: actions/checkout@v2
                with:
                    token: ${{ secrets.GH_CI_CD_RELEASE }}

            -   name: 'FontAwesome Auth ::fontawesome::'
                run: echo -e "@fortawesome:registry=https://npm.fontawesome.com/\n//npm.fontawesome.com/:_authToken=${{ secrets.FONTAWESOME_AUTH_TOKEN }}" > .npmrc

            -   name: 'Install pnpm ::package::'
                uses: pnpm/action-setup@v2
                with:
                    version: 8
                    run_install: false

            -   name: 'Install dependencies ::package::'
                run: pnpm i --shamefully-hoist

            -   name: 'Read package.json ::newspaper::'
                id: info
                uses: jaywcjlove/github-action-package@main

            -   name: 'Version Bump ::up::'
                uses: phips28/gh-action-bump-version@master
                env:
                    GITHUB_TOKEN: ${{ secrets.GH_CI_CD_RELEASE }}
                    PACKAGEJSON_DIR: $PATH
                with:
                    major-wording: 'JLMAJOR'
                    minor-wording: 'feature,feat'
                    patch-wording: 'patch,fixes,misc,docs,refactor'    # Providing patch-wording will override commits
                    commit-message: 'Release ${PACKAGE}: bumps ${{ steps.info.outputs.name }} version to {{version}} ::rocket::'

            -   name: 'Authenticate with NPM ::key::'
                run: echo -e "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

            -   name: 'Publishing package ::rocket::'
                run: cd $PATH/ && pnpm publish --access public