#
# GitHub Actions workflow.
#
# Releases the package to npm when a push into main is detected.
# * Bump version number
# * Release to NPM
#

name: 'Release: JuicyLlama Docs'

on:
    push:
        branches:
            - main
        paths:
            - 'common/docs/**'
    workflow_dispatch:

concurrency:
    group: ${{ github.ref }}

jobs:

    # Due to the way GitHub Actions works and the fact that we bump into the same repo, we need to add a turnstyle to ensure the workflows run asynchronously.
    turnstyle:
        runs-on: ubuntu-latest
        steps:
            -   name: Turnstyle
                uses: rpadaki/turnstyle@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    release:
        name: 'Release: JuicyLlama Docs'
        runs-on: ubuntu-latest
        permissions:
            contents: write
        needs:
            - turnstyle
        steps:

            -   name: 'Checkout'
                uses: actions/checkout@v4
                with:
                    token: ${{ secrets.GH_CI_CD_RELEASE }}

            -   run: git pull

            -   name: 'Install Node.js'
                uses: actions/setup-node@v3
                with:
                    node-version: 19

            -   name: 'Version Bump'
                uses: phips28/gh-action-bump-version@master
                env:
                    GITHUB_TOKEN: ${{ secrets.GH_CI_CD_RELEASE }}
                    PACKAGEJSON_DIR: common/docs
                with:
                    major-wording: 'JLMAJOR'
                    minor-wording: 'feature,feat'
                    patch-wording: 'patch,fixes,fix,misc,docs,refactor'    # Providing patch-wording will override commits
                    commit-message: 'Release Package: Hive Frontend Bump Version [skip ci]'
                    skip-tag: true

            -   name: 'Release to Amplify'
                run: |
                    URL="${{ secrets.JUICYLLAMA_DOCS_AMPLIFY_WEBHOOK_URL }}"
                    curl -X POST -d {} "$URL&operation=startbuild" -H "Content-Type: application/json"
