#
# GitHub Actions workflow.
#
# Releases the package to npm when a push into main is detected.
# * Bump version number
# * Release to NPM
#

name: 'Release: JuicyLlama Website'

on:
    push:
        branches:
            - main
        paths:
            - 'common/docs/*'
            - 'common/docs/**'
            - 'amplify.yml'
    workflow_dispatch:


jobs:

    release:
        name: 'Release: JuicyLlama Docs'
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:

            -   name: 'Checkout'
                uses: actions/checkout@v4
                with:
                    token: ${{ secrets.GH_CI_CD_RELEASE }}
                    sparse-checkout: |
                        common/docs

            -   name: 'Install Node.js'
                uses: actions/setup-node@v4
                with:
                    node-version: 18.18.2

            -   run: git stash
            -   run: git pull --force

            -   name: 'Version Bump'
                uses: phips28/gh-action-bump-version@master
                env:
                    GITHUB_TOKEN: ${{ secrets.GH_CI_CD_RELEASE }}
                    PACKAGEJSON_DIR: common/docs
                with:
                    major-wording: 'JLMAJOR'
                    minor-wording: 'feature,feat'
                    patch-wording: 'patch,fixes,fix,misc,docs,refactor'    # Providing patch-wording will override commits
                    commit-message: 'Release Package: Docs Bump Version [skip ci]'
                    skip-tag: true

            -   name: 'Release to hosting provider'
                run: |
                    URL="${{ secrets.JUICYLLAMA_WWW_RELEASE_WEBHOOK }}"
                    curl -X POST -d {} "$URL" -H "Content-Type: application/json"
