#
# GitHub Actions workflow.
#
# Releases the package to npm when a push into main is detected.
# * Bump version number
# * Release to NPM
#

name: 'Release Package: Core'

on:
    push:
        branches:
            - main
        paths:
            - 'common/core/**'
        workflow_dispatch:

jobs:

    pr_checks:
        name: 'Pre Release: Core'
        runs-on: ubuntu-latest
        steps:
            -   name: Install Node.js
                uses: actions/setup-node@v3
                with:
                    node-version: 19

            -   name: 'Checkout'
                uses: actions/checkout@v4
                with:
                    token: ${{ secrets.GH_CI_CD_RELEASE }}
                    sparse-checkout: common/core

            -   name: FontAwesome Auth
                run: echo -e "@fortawesome:registry=https://npm.fontawesome.com/\n//npm.fontawesome.com/:_authToken=${{ secrets.FONTAWESOME_AUTH_TOKEN }}" > .npmrc

            -   name: Install pnpm
                uses: pnpm/action-setup@v2
                with:
                    version: 8
                    run_install: false

            -   name: Install dependencies
                run: pnpm i --shamefully-hoist

            -   name: Lint
                run: cd common/core && pnpm run && pnpm run lint

            -   name: Build Docker Image
                run: pnpm run start:docker:build

            -   name: Test
                run: cd common/core && pnpm run test

    release:
        name: 'Release Package: Core'
        runs-on: ubuntu-latest
        needs:
            - pr_checks
        permissions:
            contents: write
        steps:
            -   name: 'Install Node.js'
                uses: actions/setup-node@v3
                with:
                    node-version: 19

            -   name: 'Checkout'
                uses: actions/checkout@v4
                with:
                    token: ${{ secrets.GH_CI_CD_RELEASE }}
                    sparse-checkout: common/core

            -   name: 'FontAwesome Auth'
                run: echo -e "@fortawesome:registry=https://npm.fontawesome.com/\n//npm.fontawesome.com/:_authToken=${{ secrets.FONTAWESOME_AUTH_TOKEN }}" > .npmrc

            -   name: 'Install pnpm'
                uses: pnpm/action-setup@v2
                with:
                    version: 8
                    run_install: false

            -   name: 'Install dependencies'
                run: pnpm i --shamefully-hoist

            -   name: 'Version Bump'
                uses: phips28/gh-action-bump-version@master
                env:
                    GITHUB_TOKEN: ${{ secrets.GH_CI_CD_RELEASE }}
                    PACKAGEJSON_DIR: common/core
                with:
                    major-wording: 'JLMAJOR'
                    minor-wording: 'feature,feat'
                    patch-wording: 'patch,fixes,fix,misc,docs,refactor'    # Providing patch-wording will override commits
                    commit-message: 'Release Package: Core Bump Version [skip ci]'
                    skip-tag: true

            -   name: 'Authenticate with NPM'
                run: echo -e "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

            -   name: 'Publishing package'
                run: cd common/core && pnpm publish --no-git-checks --access public
